### ISSUE TITLE
US.KG Panel Issue

### ISSUE THREAD

**Issue by faxxcoders** [DigitalPlatDev/US.KG-Issues#26]
**Describe the bug, issue, or problem:**  
Provide a clear and concise description of the bug or problem and steps to reproduce it.

I want to log in to my account, the username is correct, the password is correct, but I can't log in because the recaptcha error'/failed

**URL (if applicable):**  
Do not upload sensitive private content (such as URLs containing account information).

**Domain Name (if applicable):**  
Example: faxx.us.kg

**Expected Behavior:**  
Describe clearly what you expected to happen.

**Screenshots:**  
![Screenshot_2024-10-08-16-02-23-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/f1fd6430-d7fe-48ba-83aa-e4a2e270882e)

**Additional Context:**  
Add any other relevant information about the problem here.

**Comment by EdwardLab** [comment]
Since Google has adjusted the free CAPTCHA quota, it has reached the upper limit and we need to manually migrate to other CAPTCHA service providers.

{'success': False, 'error-codes': ['Over Enterprise free quota. Please ensure your project has an active billing account: https://cloud.google.com/recaptcha-enterprise/billing-information']%7D
